"""
Django settings for registro_pegogico project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os # <--- CORREGIDO: (1) OS importado para que 'os.path.join' funcione
from pathlib import Path
from dotenv import load_dotenv  # <--- Importar esto
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()  # <--- Cargar las variables del .env
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY') # <--- Cambiar esto
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.0.6', '0.0.0.0'] # Moví esto aquí arriba


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'mi_admin', # Tu aplicación personalizada
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'registro_pegogico.urls'

# tu_proyecto/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Esto busca en la carpeta 'templates' en la raíz del proyecto
        'APP_DIRS': True, # Esto busca en las carpetas 'templates' dentro de cada aplicación
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'registro_pegogico.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),      # <--- Cambiar
        'USER': os.getenv('DB_USER'),      # <--- Cambiar
        'PASSWORD': os.getenv('DB_PASSWORD'), # <--- Cambiar!!
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# La URL para acceder a los archivos estáticos en el navegador
STATIC_URL = '/static/' # <--- CORREGIDO: (2) Asegurado que tenga slashes y no esté duplicado

# Dónde Django debe buscar archivos estáticos adicionales (fuera de las apps)
# Lo dejamos vacío porque tu imagen está DENTRO de la app 'mi_admin'.
# Django la encontrará automáticamente gracias a 'APP_DIRS': True en TEMPLATES 
# y 'mi_admin' en INSTALLED_APPS.
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'static'), # <--- CORREGIDO: (3) Esta línea causaba el problema
]

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Esto es solo para producción (collectstatic)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================================================
# Configuración de Usuario y Autenticación
# =========================================================

# Especifica tu modelo de usuario personalizado
AUTH_USER_MODEL = 'mi_admin.Usuario'

# URL del login. Usa el nombre de la URL definida en tu urls.py principal.
LOGIN_URL = 'login' 

# URL a la que se redirige después de un inicio de sesión exitoso.
LOGIN_REDIRECT_URL = '/dashboard/'

# URL a la que se redirige después de un cierre de sesión exitoso.
LOGOUT_REDIRECT_URL = '/' 

# =========================================================
# Configuración de Logging
# =========================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG', # Asegúrate de que esto está en DEBUG para ver todos los mensajes
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'mi_admin': { # O el nombre de tu aplicación donde están tus vistas
            'handlers': ['console'],
            'level': 'DEBUG', # ESTO DEBE ESTAR EN DEBUG
            'propagate': False,
        },
    },
}

# =========================================================
# CONFIGURACIÓN DE CELERY
# =========================================================
# URL del Broker (Redis)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
# Aceptar contenido (usar json)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# Zona horaria
CELERY_TIMEZONE = 'America/La_Paz' # Tu zona horaria