# Generated by Django 5.1.6 on 2025-11-09 02:52

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import mi_admin.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('area', models.CharField(max_length=100)),
                ('campo', models.CharField(max_length=100)),
                ('malla', models.CharField(choices=[('TRONCAL', 'Troncal'), ('TECNICA', 'Técnica'), ('COMPLEMENTARIA', 'Complementaria')], default='TRONCAL', max_length=20)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del rol', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Ser, Saber, Hacer, Decidir', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje_total_componente', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje total que este componente aporta a la nota final (ej. Saber 35%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Tipo de Componente',
                'verbose_name_plural': 'Tipos de Componentes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='mi_admin.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveles', models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], max_length=20)),
                ('grado', models.PositiveSmallIntegerField(help_text='Ej. 1, 2, 3...')),
                ('paralelo', models.CharField(help_text='Ej. A, B, C...', max_length=2)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['niveles', 'grado', 'paralelo'],
                'unique_together': {('niveles', 'grado', 'paralelo')},
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_academico', models.IntegerField(default=2025)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.curso')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_admin.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.materia')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.CharField(help_text='Código RUDE', max_length=20, unique=True)),
                ('curso_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_actuales', to='mi_admin.curso')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Examen Unidad 1, Proyecto Final, Participación. Puede ser igual al nombre del Subcomponente si es la única evaluación.', max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateField(default=django.utils.timezone.now)),
                ('ponderacion', models.DecimalField(decimal_places=2, help_text='Puntos máximos que se pueden obtener en esta evaluación.', max_digits=5)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.asignacion')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['fecha_evaluacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_obtenida', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.estudiante')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.evaluacion')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('carnet', models.CharField(help_text='Cédula de Identidad (ej. 1234567LP)', max_length=15, unique=True, validators=[mi_admin.models.validate_carnet])),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('pais', models.CharField(blank=True, default='Bolivia', max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='mi_admin.persona'),
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='mi_admin.persona'),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrativo', to='mi_admin.persona')),
            ],
            options={
                'verbose_name': 'Administrativo',
                'verbose_name_plural': 'Administrativos',
            },
        ),
        migrations.CreateModel(
            name='Subcomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Examen Bimestral, Tareas, Lecciones, Participación', max_length=100)),
                ('porcentaje_maximo', models.DecimalField(decimal_places=2, help_text='Valor máximo de este subcomponente (ej. 15 puntos).', max_digits=5)),
                ('ponderacion_evaluacion_unica', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ponderación para una evaluación única dentro de este subcomponente (si aplica).', max_digits=5)),
                ('asignacion', models.ForeignKey(help_text='Asignación específica (Curso-Materia-Docente-Año) a la que pertenece este subcomponente.', on_delete=django.db.models.deletion.CASCADE, to='mi_admin.asignacion')),
                ('tipo_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.tipocomponente')),
            ],
            options={
                'verbose_name': 'Subcomponente',
                'verbose_name_plural': 'Subcomponentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='subcomponente',
            field=models.ForeignKey(help_text='Subcomponente al que pertenece esta evaluación.', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='mi_admin.subcomponente'),
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('gestion', models.IntegerField(help_text='Año de gestión del trimestre.')),
                ('numero', models.PositiveSmallIntegerField(blank=True, help_text='Número de trimestre (ej. 1, 2, 3)', null=True)),
            ],
            options={
                'verbose_name': 'Trimestre',
                'verbose_name_plural': 'Trimestres',
                'ordering': ['gestion', 'numero', 'fecha_inicio'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'gestion'), name='unique_trimestre_nombre_gestion'), models.UniqueConstraint(fields=('numero', 'gestion'), name='unique_trimestre_numero_gestion')],
            },
        ),
        migrations.AddField(
            model_name='subcomponente',
            name='trimestre',
            field=models.ForeignKey(help_text='Trimestre específico al que pertenece este subcomponente.', on_delete=django.db.models.deletion.CASCADE, to='mi_admin.trimestre'),
        ),
        migrations.CreateModel(
            name='ResumenTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_saber', models.DecimalField(blank=True, decimal_places=2, help_text='Nota del componente Saber.', max_digits=5, null=True)),
                ('nota_hacer', models.DecimalField(blank=True, decimal_places=2, help_text='Nota del componente Hacer.', max_digits=5, null=True)),
                ('nota_ser', models.DecimalField(blank=True, decimal_places=2, help_text='Nota del componente Ser.', max_digits=5, null=True)),
                ('nota_decidir', models.DecimalField(blank=True, decimal_places=2, help_text='Nota del componente Decidir.', max_digits=5, null=True)),
                ('prom_gral', models.DecimalField(blank=True, decimal_places=2, help_text='Promedio general del estudiante en esta materia para este trimestre.', max_digits=5, null=True)),
                ('autoeval', models.DecimalField(blank=True, decimal_places=2, help_text='Nota de autoevaluación del estudiante.', max_digits=5, null=True)),
                ('rango', models.CharField(blank=True, help_text='Rango de calificación del estudiante (ej. Excelente, Bueno).', max_length=50, null=True)),
                ('situacion', models.CharField(blank=True, help_text='Situación del estudiante (ej. Promovido, Reprobado).', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales del docente sobre el estudiante en el trimestre.', null=True)),
                ('nota_final_trimestre', models.DecimalField(blank=True, decimal_places=2, help_text='Nota final del estudiante en esta materia para este trimestre.', max_digits=5, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.asignacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.estudiante')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.trimestre')),
            ],
            options={
                'verbose_name': 'Resumen Trimestral',
                'verbose_name_plural': 'Resúmenes Trimestrales',
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.trimestre'),
        ),
        migrations.CreateModel(
            name='DesempenoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion_texto', models.TextField(blank=True, help_text='Observación detallada sobre el desempeño del estudiante para este período.', null=True)),
                ('rango_cualitativo', models.CharField(blank=True, choices=[('ED', 'En Desarrollo'), ('DA', 'Desarrollo Adecuado'), ('DO', 'Desarrollo Óptimo'), ('DP', 'Desarrollo Pleno'), ('N/A', 'No Aplica')], help_text='Clasificación cualitativa del desempeño del estudiante (Ej: ED, DA, DO, DP).', max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.asignacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenos', to='mi_admin.estudiante')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.trimestre')),
            ],
            options={
                'verbose_name': 'Desempeño del Estudiante',
                'verbose_name_plural': 'Desempeños de Estudiantes',
                'ordering': ['estudiante', 'trimestre'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asistio', models.BooleanField(default=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.asignacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_admin.estudiante')),
                ('trimestre', models.ForeignKey(help_text='Trimestre al que corresponde esta asistencia.', on_delete=django.db.models.deletion.CASCADE, to='mi_admin.trimestre')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_academico', models.PositiveSmallIntegerField(default=2025)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='mi_admin.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='mi_admin.estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-anio_academico', 'estudiante__persona__apellidos'],
                'unique_together': {('estudiante', 'anio_academico')},
            },
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(fields=('curso', 'materia', 'anio_academico'), name='unique_asignacion'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('estudiante', 'evaluacion'), name='unique_nota'),
        ),
        migrations.AlterUniqueTogether(
            name='subcomponente',
            unique_together={('tipo_componente', 'nombre', 'asignacion', 'trimestre')},
        ),
        migrations.AddConstraint(
            model_name='resumentrimestral',
            constraint=models.UniqueConstraint(fields=('estudiante', 'asignacion', 'trimestre'), name='unique_resumen_trimestral'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('asignacion', 'trimestre', 'nombre', 'subcomponente')},
        ),
        migrations.AlterUniqueTogether(
            name='desempenoestudiante',
            unique_together={('estudiante', 'asignacion', 'trimestre')},
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('estudiante', 'asignacion', 'trimestre', 'fecha'), name='unique_asistencia'),
        ),
    ]
