# Generated by Django 5.1.6 on 2025-11-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.RemoveField(
            model_name='materia',
            name='area',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='campo',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='malla',
        ),
        migrations.AddField(
            model_name='materia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
